# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.example.com:
  peer0.manufacturer.example.com:
  peer1.manufacturer.example.com:
  peer0.logistics.example.com:
  peer1.logistics.example.com:
  peer0.wholeseller.example.com:
  peer1.wholeseller.example.com:
  peer0.retailer.example.com:
  peer1.retailer.example.com:

networks:
  byfn:

services:
  ca.manufacturer.example.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-manufacturer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.manufacturer.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${MANUFACTURER_CA_PRIVATE_KEY}
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.manufacturer.example.com-cert.pem --ca.keyfile  /etc/hyperledger/fabric-ca-server-config/${MANUFACTURER_CA_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/manufacturer.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerManufacturer
    networks:
      - byfn
      
  ca.logistics.example.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-logistics
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.logistics.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${LOGISTICS_CA_PRIVATE_KEY}
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.logistics.example.com-cert.pem --ca.keyfile  /etc/hyperledger/fabric-ca-server-config/${LOGISTICS_CA_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/logistics.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerLogistics
    networks:
      - byfn      

  ca.wholeseller.example.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-wholeseller
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.wholeseller.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${WHOLESELLER_CA_PRIVATE_KEY}
    ports:
      - "9054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.wholeseller.example.com-cert.pem --ca.keyfile  /etc/hyperledger/fabric-ca-server-config/${WHOLESELLER_CA_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/wholeseller.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerWholeseller
    networks:
      - byfn
   
  ca.retailer.example.com:
    image: hyperledger/fabric-ca:$IMAGE_TAG
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-retailer
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.retailer.example.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/${RETAILER_CA_PRIVATE_KEY}
    ports:
      - "10054:7054"
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.retailer.example.com-cert.pem  --ca.keyfile  /etc/hyperledger/fabric-ca-server-config/${RETAILER_CA_PRIVATE_KEY} -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/retailer.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerRetailer
    networks:
      - byfn

  orderer.example.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.example.com
    container_name: orderer.example.com
    networks:
      - byfn

  peer0.manufacturer.example.com:
    container_name: peer0.manufacturer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.manufacturer.example.com
    networks:
      - byfn

  peer1.manufacturer.example.com:
    container_name: peer1.manufacturer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.manufacturer.example.com
    networks:
      - byfn

  peer0.logistics.example.com:
    container_name: peer0.logistics.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.logistics.example.com
    networks:
      - byfn

  peer1.logistics.example.com:
    container_name: peer1.logistics.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.logistics.example.com
    networks:
      - byfn

  peer0.wholeseller.example.com:
    container_name: peer0.wholeseller.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.wholeseller.example.com
    networks:
      - byfn

  peer1.wholeseller.example.com:
    container_name: peer1.wholeseller.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.wholeseller.example.com
    networks:
      - byfn
      
  peer0.retailer.example.com:
    container_name: peer0.retailer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.retailer.example.com
    networks:
      - byfn

  peer1.retailer.example.com:
    container_name: peer1.retailer.example.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.retailer.example.com
    networks:
      - byfn
